@startuml Parameter
skinparam Style strictuml
skinparam classAttributeIconSize 0

skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam stereotypeCBackgroundColor White
@enduml