package views_controls

// TODO Ein FensterZeichner (Renderer) ist ...
//
//	Vor.: Das Grafikpaket gfx muss im GOPATH installiert sein.
//
//	New...()
type FensterZeichner interface {
	// TODO Spezifikation...
	//
	//	Vor.: ...
	//	Eff.: ...
	Starte()
	// TODO Spezifikation...
	//
	//	Vor.: ...
	//	Eff.: ...
	Stoppe()
	SetzeFensterHintergrund(Widget)
	SetzeWidgets(...Widget)
	LayoutAnAus()
	DarkmodeAnAus()
	// TODO Spezifikation...
	//
	//	Vor.: ...
	//	Eff.: ...
	Ueberblende(Widget)
	UeberblendeText(string, string, string, uint8)
	UeberblendeAus()
}
